site_name: pgEdge Control Plane
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - scripts/generate-stack.js
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
plugins:
  - macros:
      j2_variable_start_string: '<<'
      j2_variable_end_string: '>>'
      j2_comment_start_string: '<#'
      j2_comment_end_string: '#>'
  - search
  - redoc-tag
  - gh-admonitions
theme:
  name: material
  custom_dir: docs/overrides
  logo_dark_mode: 'img/logo-dark.png'
  logo_light_mode: 'img/logo-light.png'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.prune
    - navigation.top
    - toc.follow
    - content.code.copy
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  generator: false
  version: v0.4.0
copyright: Copyright &copy; 2023 - 2025 pgEdge, Inc
repo_url: https://github.com/pgEdge/control-plane
nav:
  - Introduction: index.md
  - Concepts: concepts.md
  - Quickstart: quickstart.md
  - Installation: installation.md
  - Configuration: configuration.md
  - User Guide:
      - Creating a Database: guides/create-db.md
      - Connecting to a Database: guides/connecting.md
      - Updating a Database: guides/update-db.md
      - Upgrading a Database: guides/upgrade-db.md
      - Backup & Restore: guides/backup-restore.md
      - Tasks & Logs: guides/tasks-logs.md
      - Read Replicas: guides/read-replicas.md
      - Deleting a Database: guides/delete-db.md
      - Migrating a Database: guides/migrate-db.md
  - API:
      - OpenAPI: api/openapi.md
      - API Reference: api/reference.md
  - Development:
      - Development Process: development/development.md
      - Automated end-to-end tests: development/e2e-tests.md
      - Running locally: development/running-locally.md
